/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32_f446xx.h"

// Simple software delay
void delay_ms(uint32_t ms)
{
    for(uint32_t i = 0; i < ms; i++)
    {
        for(uint32_t j = 0; j < 1600; j++);
    }
}

int main(void)
{
    // Enable GPIOA clock
    GPIOA_CLK_EN();

    // Configure PA5 as output
    GPIOA->MODER &= ~(3U << (5 * 2));  // Clear MODER bits for PA5
    GPIOA->MODER |=  (1U << (5 * 2));  // Set PA5 as output

    while(1)
    {
        // LED ON
        GPIOA->ODR |= (1U << 5);

        delay_ms(1000);

        // LED OFF
        GPIOA->ODR &= ~(1U << 5);

        delay_ms(1000);
    }
}
