/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32_f446xx.h"
#include "uart.h"
#include "spi.h"
#include "bme280.h"

void delay_ms(uint32_t ms)
{
    for(uint32_t i = 0; i < ms; i++)
    {
        for(uint32_t j = 0; j < 1600; j++);
    }
}

/*------------------------------------------------
    Print Temperature
------------------------------------------------*/

void UART_PrintTemperature(int32_t temp)
{
    UART2_SendString("Temperature = ");

    UART2_SendNumber(temp / 100);

    UART2_SendChar('.');

    UART2_SendNumber(temp % 100);

    UART2_SendString(" C\r\n");
}

/*------------------------------------------------
    Print Pressure
------------------------------------------------*/

void UART_PrintPressure(uint32_t pressure)
{
    UART2_SendString("Pressure = ");

    UART2_SendNumber(pressure);

    UART2_SendString(" Pa\r\n");
}

/*------------------------------------------------
    MAIN
------------------------------------------------*/

int main(void)
{
    uint8_t chipID;

    int32_t temperature;

    uint32_t pressure;

    /* UART Init */

    UART2_Init();

    UART2_SendString("\r\n");
    UART2_SendString("=================================\r\n");
    UART2_SendString("STM32F446RE + BMP280 SPI\r\n");
    UART2_SendString("=================================\r\n");

    /* SPI Init */

    SPI1_Init();

    UART2_SendString("SPI Initialized\r\n");

    /* Read Chip ID */

    chipID = BMP280_ReadChipID();

    UART2_SendString("Chip ID = ");

    UART2_SendNumber(chipID);

    UART2_SendString("\r\n");

    if(chipID != 0x58)
    {
        UART2_SendString("BMP280 NOT FOUND!\r\n");

        while(1);
    }

    UART2_SendString("BMP280 FOUND\r\n");

    /* Sensor Init */

    BMP280_Init();

    UART2_SendString("BMP280 Initialized\r\n");

    while(1)
    {
        temperature = BMP280_ReadTemperature();

        pressure = BMP280_ReadPressure();

        UART_PrintTemperature(temperature);

        UART_PrintPressure(pressure);

        UART2_SendString("-------------------------\r\n");

        delay_ms(1000);
    }
}
